// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 11.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DynamicContent.TemplateGeneration.Fields.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\eganeva\Documents\GitHub\feather-widgets\DynamicContent\TemplateGeneration\Fields\Templates\AddressFieldTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public partial class AddressFieldTemplate : FieldTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n<div>\r\n    <strong> ");
            
            #line 8 "C:\Users\eganeva\Documents\GitHub\feather-widgets\DynamicContent\TemplateGeneration\Fields\Templates\AddressFieldTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FieldData.Title));
            
            #line default
            #line hidden
            this.Write(" :</strong>\r\n\r\n    <div>\r\n        <address>\r\n\t\t\t@(((Telerik.Sitefinity.GeoLocatio" +
                    "ns.Model.Address)Model.Item.");
            
            #line 12 "C:\Users\eganeva\Documents\GitHub\feather-widgets\DynamicContent\TemplateGeneration\Fields\Templates\AddressFieldTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FieldData.Name));
            
            #line default
            #line hidden
            this.Write(@").GetFormattedAddress(""#=Street# #=City# #=State# #=Country#""))
		</address>

        <div>
            <a class=""viewMapLnk"">View map</a>
            <div class=""addressMapWrp"" style=""display:none"">
                <input class=""addressValueInput"" type=""hidden"" value=""@(new JavaScriptSerializer().Serialize(Model.Item.");
            
            #line 18 "C:\Users\eganeva\Documents\GitHub\feather-widgets\DynamicContent\TemplateGeneration\Fields\Templates\AddressFieldTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FieldData.Name));
            
            #line default
            #line hidden
            this.Write(@"))"" />
                <div class=""mapContainer"" style=""width:500px; height:500px""></div>
            </div>
        </div>
    </div>
</div>

@if (Html.Sitefinity().IsApiKeyValid())
{
    @Html.Script(ScriptRef.JQuery)
    @Html.Script(""http://maps.googleapis.com/maps/api/js?key="" + Html.Sitefinity().GetApiKey() + ""&sensor=false"")
    @Html.Script(""Telerik.Sitefinity.Resources.Reference"", ""Telerik.Sitefinity.Resources.Scripts.jquery.ui.map.js"")
    <script type=""text/javascript"" src='@Url.WidgetContent(""~/Frontend-Assembly/DynamicContent/TemplateGeneration/Fields/Scripts/address-field.js"")'></script>
}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
