// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 11.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DynamicContent.TemplateGeneration.Fields.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Telerik.Sitefinity.DynamicModules.Builder.Model;
    using Telerik.Sitefinity.Frontend.Mvc.Helpers;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\eganeva\Documents\GitHub\feather-widgets\DynamicContent\TemplateGeneration\Fields\Templates\AddressFieldTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public partial class AddressFieldTemplate : FieldTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n@* Start ");
            
            #line 9 "C:\Users\eganeva\Documents\GitHub\feather-widgets\DynamicContent\TemplateGeneration\Fields\Templates\AddressFieldTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FieldData.Title));
            
            #line default
            #line hidden
            this.Write(" field *@\r\n<div>\r\n    <strong> ");
            
            #line 11 "C:\Users\eganeva\Documents\GitHub\feather-widgets\DynamicContent\TemplateGeneration\Fields\Templates\AddressFieldTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FieldData.Title));
            
            #line default
            #line hidden
            this.Write(" :</strong>\r\n\r\n\t@if(!string.IsNullOrEmpty(Model.Item.");
            
            #line 13 "C:\Users\eganeva\Documents\GitHub\feather-widgets\DynamicContent\TemplateGeneration\Fields\Templates\AddressFieldTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FieldData.Name));
            
            #line default
            #line hidden
            this.Write(".CountryCode))\r\n\t{\r\n    <div>\r\n");
            
            #line 16 "C:\Users\eganeva\Documents\GitHub\feather-widgets\DynamicContent\TemplateGeneration\Fields\Templates\AddressFieldTemplate.tt"
 if(FieldData.AddressFieldMode!=AddressFieldMode.MapOnly)
{ 
            
            #line default
            #line hidden
            this.Write("        <address>\r\n            @(((Telerik.Sitefinity.GeoLocations.Model.Address)" +
                    "Model.Item.");
            
            #line 19 "C:\Users\eganeva\Documents\GitHub\feather-widgets\DynamicContent\TemplateGeneration\Fields\Templates\AddressFieldTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FieldData.Name));
            
            #line default
            #line hidden
            this.Write(").GetFormattedAddress(\"#=Street# #=City# #=State# #=Country#\"))\r\n        </addres" +
                    "s>\r\n");
            
            #line 21 "C:\Users\eganeva\Documents\GitHub\feather-widgets\DynamicContent\TemplateGeneration\Fields\Templates\AddressFieldTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 22 "C:\Users\eganeva\Documents\GitHub\feather-widgets\DynamicContent\TemplateGeneration\Fields\Templates\AddressFieldTemplate.tt"
 if(FieldData.AddressFieldMode!=AddressFieldMode.FormOnly && FieldExtensions.IsApiKeyValid())
{ 
            
            #line default
            #line hidden
            this.Write("        <div>\r\n            <a class=\"viewMapLnk\">View map</a>\r\n            <div c" +
                    "lass=\"addressMapWrp\" style=\"display:none\">\r\n                <input class=\"addres" +
                    "sValueInput\" type=\"hidden\" value=\"@(new JavaScriptSerializer().Serialize(Model.I" +
                    "tem.");
            
            #line 27 "C:\Users\eganeva\Documents\GitHub\feather-widgets\DynamicContent\TemplateGeneration\Fields\Templates\AddressFieldTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FieldData.Name));
            
            #line default
            #line hidden
            this.Write("))\" />\r\n                <div class=\"mapContainer\" style=\"width:500px; height:500p" +
                    "x\"></div>\r\n            </div>\r\n        </div>\r\n");
            
            #line 31 "C:\Users\eganeva\Documents\GitHub\feather-widgets\DynamicContent\TemplateGeneration\Fields\Templates\AddressFieldTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("    </div>\r\n\t}\r\n</div>\r\n\r\n");
            
            #line 36 "C:\Users\eganeva\Documents\GitHub\feather-widgets\DynamicContent\TemplateGeneration\Fields\Templates\AddressFieldTemplate.tt"
 if (FieldData.AddressFieldMode!=AddressFieldMode.FormOnly && FieldExtensions.IsApiKeyValid())
{ 
            
            #line default
            #line hidden
            this.Write(@"@Html.Script(ScriptRef.JQuery)
@Html.Script(""http://maps.googleapis.com/maps/api/js?key="" + Html.Sitefinity().GetApiKey() + ""&sensor=false"")
@Html.Script(""Telerik.Sitefinity.Resources.Reference"", ""Telerik.Sitefinity.Resources.Scripts.jquery.ui.map.js"")
<script type=""text/javascript"" src='@Url.WidgetContent(""~/Frontend-Assembly/DynamicContent/TemplateGeneration/Fields/Scripts/address-field.js"")'></script>
");
            
            #line 42 "C:\Users\eganeva\Documents\GitHub\feather-widgets\DynamicContent\TemplateGeneration\Fields\Templates\AddressFieldTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("@* End ");
            
            #line 43 "C:\Users\eganeva\Documents\GitHub\feather-widgets\DynamicContent\TemplateGeneration\Fields\Templates\AddressFieldTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FieldData.Title));
            
            #line default
            #line hidden
            this.Write(" field *@");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
