// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 11.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DynamicContent.TemplateGeneration.Fields.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\eganeva\Documents\GitHub\feather-widgets\DynamicContent\TemplateGeneration\Fields\Templates\DateFieldTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public partial class DateFieldTemplate : FieldTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n@* Start ");
            
            #line 7 "C:\Users\eganeva\Documents\GitHub\feather-widgets\DynamicContent\TemplateGeneration\Fields\Templates\DateFieldTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FieldData.Title));
            
            #line default
            #line hidden
            this.Write(" field *@\r\n<div>\r\n    <strong> ");
            
            #line 9 "C:\Users\eganeva\Documents\GitHub\feather-widgets\DynamicContent\TemplateGeneration\Fields\Templates\DateFieldTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FieldData.Title));
            
            #line default
            #line hidden
            this.Write(" :</strong>\r\n\r\n    @if(Model.Item.");
            
            #line 11 "C:\Users\eganeva\Documents\GitHub\feather-widgets\DynamicContent\TemplateGeneration\Fields\Templates\DateFieldTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FieldData.Name));
            
            #line default
            #line hidden
            this.Write("!=null)\r\n    {\r\n    <span data-sf-field=\"");
            
            #line 13 "C:\Users\eganeva\Documents\GitHub\feather-widgets\DynamicContent\TemplateGeneration\Fields\Templates\DateFieldTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FieldData.Name));
            
            #line default
            #line hidden
            this.Write("\" data-sf-ftype=\"DateTime\">\r\n        @(((DateTime)Model.Item.@FieldData.Name).ToS" +
                    "itefinityUITime().ToString(\"MMM d, yyyy, HH:mm tt\"))\r\n    </span>\r\n    } \r\n</div" +
                    ">\r\n@* End ");
            
            #line 18 "C:\Users\eganeva\Documents\GitHub\feather-widgets\DynamicContent\TemplateGeneration\Fields\Templates\DateFieldTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FieldData.Title));
            
            #line default
            #line hidden
            this.Write(" field *@");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
