// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 11.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DynamicContent.TemplateGeneration.Fields.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\eganeva\Documents\GitHub\feather-widgets\DynamicContent\TemplateGeneration\Fields\Templates\DateFieldTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public partial class DateFieldTemplate : FieldTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n<div>\r\n    <strong> ");
            
            #line 8 "C:\Users\eganeva\Documents\GitHub\feather-widgets\DynamicContent\TemplateGeneration\Fields\Templates\DateFieldTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FieldData.Title));
            
            #line default
            #line hidden
            this.Write(" :</strong>\r\n\r\n\t@if(Model.Item.");
            
            #line 10 "C:\Users\eganeva\Documents\GitHub\feather-widgets\DynamicContent\TemplateGeneration\Fields\Templates\DateFieldTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FieldData.Name));
            
            #line default
            #line hidden
            this.Write("!=null)\r\n\t{\r\n    <span data-sf-field=\"");
            
            #line 12 "C:\Users\eganeva\Documents\GitHub\feather-widgets\DynamicContent\TemplateGeneration\Fields\Templates\DateFieldTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FieldData.Name));
            
            #line default
            #line hidden
            this.Write("\" data-sf-ftype=\"DateTime\">\r\n\t\t@(((DateTime)Model.Item.");
            
            #line 13 "C:\Users\eganeva\Documents\GitHub\feather-widgets\DynamicContent\TemplateGeneration\Fields\Templates\DateFieldTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FieldData.Name));
            
            #line default
            #line hidden
            this.Write(").ToSitefinityUITime().ToString(\"MMM d, yyyy, HH:mm tt\"))\r\n\t</span>\r\n\t} \r\n</div>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
